server:
  port: 8889
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rockycta/automobile-configrepo2.git
          default-label: master
  application:
    name: ConfigServer

